-- SmartCampus LMS schema for Supabase PostgreSQL.
-- Run this in Supabase Dashboard > SQL Editor, or with psql using a privileged database password.

create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(50) not null check (role in ('STUDENT', 'TEACHER', 'ADMIN'))
);

create table if not exists department (
    id bigint generated by default as identity primary key,
    dept_name varchar(255) not null unique
);

create table if not exists batch (
    id bigint generated by default as identity primary key,
    dept_id bigint not null references department(id),
    batch_year date not null,
    batch_name varchar(100) not null
);

create table if not exists course (
    id bigint generated by default as identity primary key,
    course_name varchar(255) not null,
    course_code varchar(50) not null unique,
    credit integer not null,
    course_type varchar(50) not null check (course_type in ('THEORY', 'LAB'))
);

create table if not exists course_for_depts (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course(id),
    dept_id bigint not null references department(id),
    sem integer not null check (sem between 1 and 8),
    unique (course_id, dept_id, sem)
);

create table if not exists student (
    id bigint generated by default as identity primary key,
    roll_number varchar(50) not null unique,
    name varchar(255) not null,
    dob date not null,
    gender varchar(20),
    address text,
    dept_id bigint not null references department(id),
    batch_id bigint not null references batch(id),
    batch_year integer not null,
    current_year integer not null check (current_year between 1 and 4),
    current_semester integer not null check (current_semester between 1 and 8),
    email varchar(255) not null unique,
    phone varchar(20),
    blood_group varchar(10),
    mother_tongue varchar(50),
    nationality varchar(50)
);

create table if not exists father_details (
    student_id bigint primary key references student(id) on delete cascade,
    name varchar(255),
    phone varchar(20),
    email varchar(255),
    occupation varchar(255),
    annual_income varchar(100),
    address text
);

create table if not exists mother_details (
    student_id bigint primary key references student(id) on delete cascade,
    name varchar(255),
    phone varchar(20),
    email varchar(255),
    occupation varchar(255),
    annual_income varchar(100),
    address text
);

create table if not exists identity_details (
    student_id bigint primary key references student(id) on delete cascade,
    aadhar_number varchar(50),
    pan_number varchar(50),
    passport_number varchar(50)
);

create table if not exists teacher (
    id bigint generated by default as identity primary key,
    teacher_clg_id varchar(50) not null unique,
    name varchar(255) not null,
    email varchar(255) not null unique,
    phone varchar(20),
    username varchar(100),
    account_status varchar(50) default 'ACTIVE',
    last_login timestamp
);

create table if not exists teacher_personal_details (
    teacher_id bigint primary key references teacher(id) on delete cascade,
    gender varchar(20),
    date_of_birth date,
    blood_group varchar(10),
    address text
);

create table if not exists teacher_employment_details (
    teacher_id bigint primary key references teacher(id) on delete cascade,
    department_id bigint not null references department(id),
    designation varchar(100),
    employment_type varchar(100),
    joining_date date,
    experience_years varchar(50),
    office_location varchar(100),
    staff_type varchar(100)
);

create table if not exists teacher_qualification_details (
    id bigint generated by default as identity primary key,
    teacher_id bigint not null references teacher(id) on delete cascade,
    ug_degree varchar(100),
    pg_degree varchar(100),
    phd_status varchar(50),
    specialization varchar(255),
    university_name varchar(255),
    year_of_passing integer
);

create table if not exists teacher_research_publications (
    teacher_id bigint primary key references teacher(id) on delete cascade,
    papers_published integer not null default 0,
    conferences_attended integer not null default 0,
    workshops_attended integer not null default 0,
    patents integer not null default 0,
    funded_projects integer not null default 0
);

create table if not exists teacher_leave_balance (
    teacher_id bigint primary key references teacher(id) on delete cascade,
    casual_leave_balance integer not null default 12,
    medical_leave_balance integer not null default 10,
    earned_leave_balance integer not null default 30
);

create table if not exists course_teacher_allocation (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course(id) on delete cascade,
    teacher_id bigint not null references teacher(id) on delete cascade,
    unique (course_id, teacher_id)
);

create table if not exists student_course_teacher (
    student_id bigint not null references student(id) on delete cascade,
    course_id bigint not null references course(id) on delete cascade,
    teacher_id bigint not null references teacher(id) on delete cascade,
    semester integer not null,
    status varchar(50) default 'ACTIVE' check (status in ('ACTIVE', 'COMPLETED')),
    primary key (student_id, course_id, teacher_id, semester)
);

create table if not exists course_material (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course(id) on delete cascade,
    teacher_id bigint not null references teacher(id) on delete cascade,
    title varchar(255) not null,
    module varchar(100),
    material_type varchar(50) not null,
    description text,
    original_filename varchar(255) not null,
    stored_filename varchar(255) not null,
    stored_path varchar(512) not null,
    mime_type varchar(100),
    file_size bigint,
    publish_at timestamp,
    expiry_at timestamp,
    download_allowed smallint not null default 1 check (download_allowed in (0, 1)),
    created_at timestamp not null default current_timestamp
);

create table if not exists course_assignment (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course(id) on delete cascade,
    teacher_id bigint not null references teacher(id) on delete cascade,
    title varchar(255) not null,
    assignment_mode varchar(50) not null check (assignment_mode in ('FILE', 'TEXT')),
    question_text text,
    instructions text,
    original_filename varchar(255),
    stored_filename varchar(255),
    stored_path varchar(512),
    mime_type varchar(100),
    file_size bigint,
    due_at timestamp,
    max_marks integer,
    download_allowed smallint not null default 1 check (download_allowed in (0, 1)),
    is_published smallint not null default 1 check (is_published in (0, 1)),
    created_at timestamp not null default current_timestamp
);

create table if not exists course_assignment_submission (
    id bigint generated by default as identity primary key,
    assignment_id bigint not null references course_assignment(id) on delete cascade,
    student_id bigint not null references student(id) on delete cascade,
    original_filename varchar(255) not null,
    stored_filename varchar(255) not null,
    stored_path varchar(512) not null,
    mime_type varchar(100),
    file_size bigint,
    submitted_at timestamp not null default current_timestamp,
    unique (assignment_id, student_id)
);

create table if not exists quiz (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course(id) on delete cascade,
    teacher_id bigint not null references teacher(id) on delete cascade,
    title varchar(255) not null,
    instructions text,
    total_marks integer not null,
    duration_minutes integer not null,
    start_at timestamp not null,
    end_at timestamp not null,
    is_published smallint not null default 1 check (is_published in (0, 1)),
    is_score_published smallint not null default 0 check (is_score_published in (0, 1)),
    created_at timestamp not null default current_timestamp
);

create table if not exists quiz_question (
    id bigint generated by default as identity primary key,
    quiz_id bigint not null references quiz(id) on delete cascade,
    question_order integer not null,
    question_text text not null,
    question_type varchar(50) not null check (question_type in ('MCQ', 'DESCRIPTIVE')),
    marks integer not null default 1,
    correct_option_index integer
);

create table if not exists quiz_option (
    id bigint generated by default as identity primary key,
    question_id bigint not null references quiz_question(id) on delete cascade,
    option_index integer not null,
    option_text text not null,
    unique (question_id, option_index)
);

create table if not exists quiz_submission (
    id bigint generated by default as identity primary key,
    quiz_id bigint not null references quiz(id) on delete cascade,
    student_id bigint not null references student(id) on delete cascade,
    submitted_at timestamp not null default current_timestamp,
    score integer not null default 0,
    unique (quiz_id, student_id)
);

create table if not exists quiz_answer (
    id bigint generated by default as identity primary key,
    submission_id bigint not null references quiz_submission(id) on delete cascade,
    question_id bigint not null references quiz_question(id) on delete cascade,
    selected_option_index integer,
    answer_text text,
    marks_awarded integer,
    unique (submission_id, question_id)
);

create table if not exists feedback_form (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course(id) on delete cascade,
    teacher_id bigint not null references teacher(id) on delete cascade,
    title varchar(255) not null,
    description text,
    is_active smallint not null default 1 check (is_active in (0, 1)),
    created_at timestamp not null default current_timestamp
);

create table if not exists feedback_question (
    id bigint generated by default as identity primary key,
    form_id bigint not null references feedback_form(id) on delete cascade,
    question_order integer not null,
    question_text text not null,
    question_type varchar(50) not null check (question_type in ('RATING', 'MCQ', 'TEXT')),
    options_text text,
    rating_max integer,
    required smallint not null default 1 check (required in (0, 1))
);

create table if not exists feedback_submission (
    id bigint generated by default as identity primary key,
    form_id bigint not null references feedback_form(id) on delete cascade,
    student_id bigint not null references student(id) on delete cascade,
    submitted_at timestamp not null default current_timestamp,
    unique (form_id, student_id)
);

create table if not exists feedback_answer (
    id bigint generated by default as identity primary key,
    submission_id bigint not null references feedback_submission(id) on delete cascade,
    question_id bigint not null references feedback_question(id) on delete cascade,
    answer_text text,
    answer_number integer,
    unique (submission_id, question_id)
);

insert into users (email, password, role)
values ('admin@smartcampus.local', 'admin', 'ADMIN')
on conflict (email) do nothing;

create index if not exists idx_batch_dept_id on batch(dept_id);
create index if not exists idx_student_dept_batch on student(dept_id, batch_id);
create index if not exists idx_teacher_email on teacher(email);
create index if not exists idx_course_for_depts_lookup on course_for_depts(dept_id, sem);
create index if not exists idx_course_teacher_allocation_teacher on course_teacher_allocation(teacher_id);
create index if not exists idx_student_course_teacher_course_teacher on student_course_teacher(course_id, teacher_id);
create index if not exists idx_course_material_course_teacher on course_material(course_id, teacher_id);
create index if not exists idx_course_assignment_course_teacher on course_assignment(course_id, teacher_id);
create index if not exists idx_quiz_course_teacher on quiz(course_id, teacher_id);
create index if not exists idx_feedback_form_course_teacher on feedback_form(course_id, teacher_id);
