INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (1, 'HS23111', 'Technical Communication I', 2, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (2, 'MA23111', 'Linear Algebra and Calculus', 4, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (3, 'MA23116', 'Mathematical Foundations for AI', 4, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (4, 'MA23213', 'Discrete Mathematical Structures', 4, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (5, 'MA23214', 'Probability and Inferential Statistics', 4, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (6, 'MA23312', 'Fourier Series and Number Theory', 4, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (7, 'MA23313', 'Discrete Mathematics for AI', 4, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (8, 'GE23117', 'Heritage of Tamils', 1, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (9, 'GE23217', 'Tamils and Technology', 1, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (10, 'GE23311', 'Fundamentals of Management for Engineers', 3, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (11, 'CS23511', 'Theory of Computation', 4, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (12, 'CS23512', 'Fundamentals of Mobile Computing', 3, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (13, 'AI23512', 'Data Engineering', 3, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (14, 'AI23611', 'Secure Systems Engineering', 3, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (15, 'AI23711', 'Social and Ethical Issues in AI', 1, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (16, 'AI23712', 'Reinforcement Learning', 3, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (17, 'GE23131', 'Programming using C', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (18, 'GE23111', 'Engineering Graphics', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (19, 'PH23132', 'Physics for Information Science', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (20, 'EE23133', 'Basic Electrical and Electronics Engineering', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (21, 'EE23233', 'Basic Electrical and Electronics Engineering', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (22, 'EC23232', 'Digital Logic and Microprocessor', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (23, 'EC23331', 'Microprocessors and Microcontroller', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (24, 'EC23314', 'Analog and Digital Communication', 3, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (25, 'IT23331', 'Digital Logic and Computer Architecture', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (26, 'IT23231', 'Digital Principles and Computer Architecture', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (27, 'CS23231', 'Data Structures', 5, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (28, 'CS23331', 'Design and Analysis of Algorithms', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (29, 'CS23332', 'Database Management Systems', 5, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (30, 'CS23333', 'Object Oriented Programming using Java', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (31, 'CS23334', 'Fundamentals of Data Science', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (32, 'CS23431', 'Operating Systems', 5, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (33, 'CS23432', 'Software Construction', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (34, 'MA23434', 'Optimization Techniques for AI', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (35, 'MA23435', 'Probability, Statistics and Simulation', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (36, 'AI23231', 'Principles of Artificial Intelligence', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (37, 'AI23331', 'Fundamentals of Machine Learning', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (38, 'AI23431', 'Web Technology and Mobile Application', 3, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (39, 'AI23531', 'Deep Learning', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (40, 'AI23631', 'Predictive and Prescriptive Analytics', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (41, 'AI23632', 'Natural Language Processing', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (42, 'CS23531', 'Web Programming', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (43, 'CS23532', 'Computer Networks', 5, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (44, 'CS23631', 'Compiler Design', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (45, 'CS23632', 'Cryptography and Network Security', 3, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (46, 'CS23633', 'Cloud Computing', 3, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (47, 'CS23634', 'Fundamentals of Generative AI and Prompt Engineering', 3, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (48, 'IT23431', 'MongoDB Essentials', 3, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (49, 'IT23531', 'Computer Vision', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (50, 'IT23731', 'Cloud and Big Data Architecture', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (51, 'AD23632', 'Framework for Data and Visual Analytics', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (52, 'GE23121', 'Engineering Practices - Civil and Mechanical', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (53, 'GE23122', 'Engineering Practices - Electrical and Electronics', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (54, 'CS23221', 'Python Programming Lab', 2, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (55, 'HS23221', 'Technical Communication II', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (56, 'HS23222', 'English for Professional Competence', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (57, 'GE23421', 'Soft Skills - I', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (58, 'GE23521', 'Soft Skills - II', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (59, 'GE23621', 'Problem Solving Techniques', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (60, 'GE23627', 'Design Thinking and Innovation', 2, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (61, 'CS23621', 'Mobile Application Development Laboratory', 2, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (62, 'IT23721', 'Data Science using R', 2, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (63, 'AI23521', 'Build and Deploy Machine Learning Applications', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (64, 'AI23721', 'Project Phase I', 4, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (67, 'AI23821', 'Project Phase II', 6, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (70, 'MC23111', 'Indian Constitution and Freedom Movement', 0, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (71, 'MC23112', 'Environmental Science and Engineering', 0, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (72, 'AD23431', 'Statistical Analysis and Computing', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (73, 'AD23421', 'Internship', 2, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (74, 'OE23401', 'Open Elective', 3, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (75, 'AD23531', 'Big Data Architecture', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (76, 'AD23532', 'Principles of Data Science', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (79, 'AD23631', 'Data Privacy and Security', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (95, 'PE00000', 'Professional Elective', 3, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (96, 'CS23311', 'Computer Architecture', 3, 'THEORY');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (97, 'CS23421', 'Internship (2 weeks)', 1, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (98, 'CS23533', 'Foundations of Artificial Intelligence', 4, 'LOT');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (99, 'CS23721', 'Project Phase I', 3, 'LAB');
INSERT INTO smartcampus.course (id, course_code, course_name, credit, course_type) VALUES (100, 'CS23821', 'Project Phase II', 6, 'LAB');
